<?= $this->extend('admin/layouts/main') ?>
<?= $this->section('content') ?>
<?php $status = (string) ($requirement['status'] ?? ''); ?>
<div class="erp-page-shell">
    <div class="erp-toolbar mb-4"><div class="erp-toolbar-copy"><span class="erp-eyebrow">Diamond requirement</span><h4><?= esc((string) $requirement['requirement_no']) ?></h4><p>Order <?= esc((string) $requirement['order_no']) ?> · <?= esc(ucwords(str_replace('_', ' ', $status))) ?></p></div><div class="d-flex gap-2"><a href="<?= site_url('admin/orders/' . (int) $requirement['order_id']) ?>" class="btn btn-outline-primary">Order Details</a><a href="<?= site_url('admin/diamond-inventory/requirements') ?>" class="btn btn-light">Back</a></div></div>
    <div class="row g-4">
        <div class="col-lg-5"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Workflow</h5></div><div class="card-body">
            <?php foreach ([['Order', $requirement['order_no'] ?? '-'], ['Order Name', $requirement['order_name'] ?? '-'], ['Raised By', $requirement['requester_name'] ?? '-'], ['Requirement', $requirement['requirement_note'] ?? '-'], ['Required By', $requirement['required_by'] ?? '-'], ['Approved By', $requirement['approver_name'] ?? '-'], ['Assigned To', $requirement['assignee_name'] ?? '-'], ['Preparation Due', $requirement['preparation_due_at'] ?? '-'], ['Ready By', $requirement['ready_by_name'] ?? '-'], ['Ready At', $requirement['ready_at'] ?? '-']] as [$label, $value]): ?><div class="d-flex justify-content-between gap-3 border-bottom py-2"><span class="text-muted"><?= esc((string) $label) ?></span><strong class="text-end"><?= esc((string) (($value ?? '') ?: '-')) ?></strong></div><?php endforeach; ?>
            <?php if ($status === 'pending_approval'): ?><button class="btn btn-primary w-100 mt-4" data-bs-toggle="modal" data-bs-target="#approveRequirement">Approve &amp; Assign</button><?php endif; ?>
        </div></div></div>
        <div class="col-lg-7"><div class="card h-100"><div class="card-header d-flex justify-content-between"><h5 class="mb-0">Prepared Bag</h5><?php if (! empty($requirement['bag_id'])): ?><a href="<?= site_url('admin/diamond-inventory/bags/' . (int) $requirement['bag_id']) ?>" class="btn btn-sm btn-outline-primary"><?= esc((string) $requirement['bag_no']) ?></a><?php endif; ?></div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Diamond</th><th>Shape</th><th>Size</th><th>PCS</th><th>CTS</th><th>Available</th></tr></thead><tbody>
            <?php foreach (($bagItems ?? []) as $item): ?><tr><td><?= esc((string) ($item['diamond_type'] ?? '-')) ?></td><td><?= esc((string) ($item['shape_name'] ?? '-')) ?></td><td><?= esc((string) (($item['size_label'] ?? '') ?: ($item['size_code'] ?? '-'))) ?></td><td><?= number_format((float) ($item['pcs_total'] ?? 0), 0) ?></td><td><?= number_format((float) ($item['weight_cts_total'] ?? 0), 3) ?></td><td><?= number_format((float) ($item['pcs_available'] ?? 0), 0) ?> pcs · <?= number_format((float) ($item['weight_cts_available'] ?? 0), 3) ?> cts</td></tr><?php endforeach; ?>
            <?php if (($bagItems ?? []) === []): ?><tr><td colspan="6" class="text-center text-muted py-5"><?= $status === 'assigned' ? 'Assigned staff will add shape-wise PCS and CTS from the mobile app.' : 'Bag has not been prepared yet.' ?></td></tr><?php endif; ?>
            </tbody></table></div></div></div></div>
    </div>
</div>
<?php if ($status === 'pending_approval'): ?><?php $defaultDue = ! empty($requirement['required_by']) ? (string) $requirement['required_by'] . 'T18:00' : date('Y-m-d\T18:00', strtotime('+1 day')); ?><div class="modal fade" id="approveRequirement" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="post" action="<?= site_url('admin/diamond-inventory/requirements/' . (int) $requirement['id'] . '/approve') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Approve &amp; Assign</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Bag preparation staff *</label><select name="assigned_to" class="form-select" required><option value="">Select staff</option><?php foreach (($staff ?? []) as $user): ?><option value="<?= (int) $user['id'] ?>"><?= esc((string) $user['name']) ?> · <?= esc((string) $user['email']) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Due date &amp; time *</label><input type="datetime-local" name="preparation_due_at" class="form-control" required value="<?= esc($defaultDue) ?>"><div class="form-text">The assigned staff task must be completed by this time.</div></div><label class="form-label">Approval note</label><textarea name="approval_note" class="form-control" rows="3"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Approve &amp; Notify</button></div></form></div></div><?php endif; ?>
<?= $this->endSection() ?>
