<?= $this->extend('customer/layout') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-end mb-4"><div><span class="eyebrow">New request</span><h2 class="mb-1">Create Order</h2><p class="text-muted mb-0">Add a fresh concept or repeat an existing unique design.</p></div><a href="<?= site_url('customer/orders') ?>" class="btn btn-outline-dark">Back</a></div>
<form method="post" action="<?= site_url('customer/orders') ?>" enctype="multipart/form-data"><?= csrf_field() ?><div class="portal-card card"><div class="card-body p-4 p-lg-5"><div class="row g-3">
<div class="col-md-4"><label class="form-label">Order Type</label><select name="order_type" class="form-select js-searchable-select" required><option value="Manufacturing">Manufacturing</option><option value="Sales">Sales</option><option value="Repair">Repair</option></select></div>
<div class="col-md-4"><label class="form-label">Fresh or Repeat</label><select name="order_design_type" id="design-type" class="form-select js-searchable-select" required><option value="Fresh">Fresh Order</option><option value="Repeat">Repeat Order</option></select></div>
<?php if(!$isSalesPerson):?><div class="col-md-4"><label class="form-label">Sales Person</label><select name="sales_person_user_id" id="sales-person" class="form-select js-searchable-select" data-placeholder="Search sales person"><option value=""></option><?php foreach($salesPeople as$person):?><option value="<?= (int)$person['id'] ?>" data-mobile="<?= esc((string)$person['mobile'],'attr') ?>"><?= esc($person['name'].' · '.($person['mobile']?:'No mobile')) ?></option><?php endforeach;?></select><div id="sales-person-detail" class="form-text"></div></div><?php endif;?>
<div class="col-12" id="repeat-design-wrap" style="display:none"><label class="form-label">Unique Design Code</label><select name="design_id" id="design-select" class="form-select js-searchable-select" data-placeholder="Search design code"><option value=""></option><?php foreach($designs as$d):?><option value="<?= (int)$d['id'] ?>"><?= esc($d['design_code'].' · '.$d['name'].' · '.($d['subcategory']?:$d['category'])) ?></option><?php endforeach;?></select></div>
<div class="col-md-8"><label class="form-label">Item / Design Details</label><input name="item_description" class="form-control" value="<?= esc(old('item_description')) ?>" placeholder="Ring, jhumki, haaram, specifications…" required></div><div class="col-md-2"><label class="form-label">Size</label><input name="size_label" class="form-control" value="<?= esc(old('size_label')) ?>"></div><div class="col-md-2"><label class="form-label">Qty</label><input type="number" name="qty" min="1" value="1" class="form-control" required></div>
<div class="col-md-3"><label class="form-label">Expected Gold (gm)</label><input type="number" step=".001" min="0" name="gold_required_gm" value="0" class="form-control"></div><div class="col-md-3"><label class="form-label">Expected Diamond (cts)</label><input type="number" step=".001" min="0" name="diamond_required_cts" value="0" class="form-control"></div><div class="col-md-3"><label class="form-label">Required By</label><input type="date" name="due_date" class="form-control"></div><div class="col-md-3"><label class="form-label">Reference Photos</label><input type="file" name="order_images[]" accept="image/*" multiple class="form-control"><div class="form-text">Up to 10 images, 5 MB each.</div></div>
<div class="col-12"><label class="form-label">Notes</label><textarea name="order_notes" rows="3" class="form-control"><?= esc(old('order_notes')) ?></textarea></div><div class="col-12 pt-2"><button class="btn btn-dark btn-lg px-5">Submit Order</button></div>
</div></div></div></form>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script>(function(){const type=document.getElementById('design-type'),wrap=document.getElementById('repeat-design-wrap'),design=document.getElementById('design-select'),sales=document.getElementById('sales-person'),detail=document.getElementById('sales-person-detail');function toggle(){const repeat=type&&type.value==='Repeat';if(wrap)wrap.style.display=repeat?'':'none';if(design)design.required=repeat;}if(type){jQuery(type).on('change',toggle);toggle();}if(sales){jQuery(sales).on('change',function(){const o=sales.options[sales.selectedIndex];detail.textContent=o&&o.value?'Mobile: '+(o.dataset.mobile||'Not available'):'';});}})();</script><?= $this->endSection() ?>
