<?= $this->extend('admin/layouts/main') ?>

<?= $this->section('content') ?>
<style>
.dc-create-hero{background:linear-gradient(135deg,#351528,#733149);color:#fff;border-radius:18px;padding:24px 28px;box-shadow:0 16px 40px rgba(53,21,40,.18)}.dc-create-hero h3{color:#fff}.dc-section{border:1px solid #eadfce;border-radius:16px;box-shadow:0 10px 30px rgba(66,29,50,.06)}.dc-section .card-header{background:#fffaf0;border-bottom:1px solid #eadfce}.dc-total{border-radius:14px;background:#351528;color:#fff;padding:18px}.dc-total strong{font:700 24px Georgia;color:#e7bd68}.item-line{background:#fff;border:1px solid #e9e2dc;border-radius:14px;padding:16px;margin-bottom:14px}.line-label{font-size:11px;text-transform:uppercase;letter-spacing:.7px;color:#80747c;font-weight:700}
</style>
<form method="post" action="<?= site_url('admin/delivery-challans') ?>" id="dc-form"><?= csrf_field() ?>
<div class="dc-create-hero mb-4"><div class="d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><div class="small text-uppercase fw-bold mb-1" style="letter-spacing:2px;color:#e7bd68">Dispatch Note</div><h3 class="mb-1">Create Delivery Challan</h3><div class="text-white-50">Inventory-independent multi-material challan</div></div><div class="text-end"><div class="small text-white-50">Automatic Challan No.</div><div class="fs-3 fw-bold" style="font-family:Georgia;color:#e7bd68"><?= esc((string) ($next_challan_no ?? 'DC0001')) ?></div></div></div></div>

<div class="card dc-section mb-4"><div class="card-header"><h5 class="mb-0">Dispatch & Customer</h5></div><div class="card-body"><div class="row g-3">
<div class="col-md-3"><label class="form-label">Challan Date *</label><input type="date" name="challan_date" class="form-control" required value="<?= esc((string) old('challan_date', date('Y-m-d'))) ?>"></div>
<div class="col-md-4"><label class="form-label">Dispatch From *</label><select name="dispatch_from" id="dispatch-from" class="form-select" required><option value="">Select branch</option><?php foreach (($branches ?? []) as $branch): ?><option value="<?= esc((string) $branch['key']) ?>" data-address="<?= esc((string) $branch['address']) ?>"><?= esc((string) $branch['name']) ?></option><?php endforeach; ?></select><div id="branch-address" class="small text-muted mt-2"></div></div>
<div class="col-md-5"><label class="form-label">Customer *</label><select name="customer_id" id="customer-id" class="form-select js-select2" required><option value="">Select customer</option><?php foreach (($customers ?? []) as $customer): ?><option value="<?= (int) $customer['id'] ?>" data-address="<?= esc((string) ($customer['address'] ?? '')) ?>" data-gstin="<?= esc((string) ($customer['gstin'] ?? '')) ?>"><?= esc((string) ($customer['name'] ?? '-')) ?><?= ! empty($customer['customer_code']) ? ' · ' . esc((string) $customer['customer_code']) : '' ?></option><?php endforeach; ?></select><div id="customer-detail" class="small text-muted mt-2"></div></div>
</div></div></div>

<div class="card dc-section mb-4"><div class="card-header d-flex justify-content-between align-items-center"><div><h5 class="mb-1">Challan Contents</h5><small class="text-muted">Ornament, loose diamond and loose gold can be combined.</small></div><button type="button" class="btn btn-primary" id="add-line"><i class="fe fe-plus me-1"></i>Add Item</button></div><div class="card-body" id="item-lines"></div></div>

<div class="card dc-section mb-4"><div class="card-header"><h5 class="mb-0">Value & GST</h5></div><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">GST Rate *</label><select name="tax_percent" id="tax-percent" class="form-select"><?php foreach (($gst_rates ?? [0,3,5,12,18]) as $rate): ?><option value="<?= esc((string) $rate) ?>" <?= (float) $rate === 3.0 ? 'selected' : '' ?>><?= number_format((float) $rate, 0) ?>%</option><?php endforeach; ?></select></div><div class="col-md-5"><label class="form-label">Notes</label><input name="notes" class="form-control" maxlength="1000" placeholder="Purpose, reference or dispatch instructions"></div><div class="col-md-4"><div class="dc-total"><div class="d-flex justify-content-between"><span>Item Value</span><span id="taxable-total">₹0.00</span></div><div class="d-flex justify-content-between"><span>GST</span><span id="gst-total">₹0.00</span></div><hr style="border-color:rgba(255,255,255,.25)"><div class="d-flex justify-content-between align-items-center"><span>Gross Total</span><strong id="gross-total">₹0.00</strong></div></div></div></div></div></div>
<div class="d-flex justify-content-end gap-2"><a href="<?= site_url('admin/delivery-challans') ?>" class="btn btn-light">Cancel</a><button class="btn btn-primary btn-lg"><i class="fe fe-file-text me-1"></i>Create & Save Challan</button></div>
</form>

<template id="line-template"><div class="item-line"><div class="d-flex justify-content-between align-items-center mb-3"><strong class="line-title">Item</strong><button type="button" class="btn btn-sm btn-light text-danger remove-line"><i class="fe fe-trash-2"></i></button></div><div class="row g-3">
<div class="col-md-3"><div class="line-label mb-1">Item Type *</div><select name="item_type[]" class="form-select item-type" required><option value="ornament">Ornament</option><option value="loose_diamond">Loose Diamond</option><option value="loose_gold">Loose Gold / Metal</option></select></div>
<div class="col-md-5"><div class="line-label mb-1">Description</div><input name="description[]" class="form-control" maxlength="180" placeholder="Item description"></div>
<div class="col-md-2 purity-field"><div class="line-label mb-1">Purity *</div><select name="purity[]" class="form-select"><option value="18 KT">18 KT</option><option value="22 KT">22 KT</option><option value="14 KT">14 KT</option></select></div>
<div class="col-md-2"><div class="line-label mb-1">PCS *</div><input type="number" name="pcs[]" class="form-control" min="1" step="1" value="1" required></div>
<div class="col-md-2 ornament-field"><div class="line-label mb-1">Gross Weight (gm) *</div><input type="number" name="gross_weight_gm[]" class="form-control" min="0" step="0.001" value="0"></div>
<div class="col-md-2 metal-field"><div class="line-label mb-1 net-label">Net Weight (gm) *</div><input type="number" name="net_weight_gm[]" class="form-control" min="0" step="0.001" value="0"></div>
<div class="col-md-2 diamond-field"><div class="line-label mb-1">Diamond Weight (ct) *</div><input type="number" name="diamond_weight_cts[]" class="form-control" min="0" step="0.001" value="0"></div>
<div class="col-md-2 ornament-field"><div class="line-label mb-1">Stone Weight (ct)</div><input type="number" name="stone_weight_cts[]" class="form-control" min="0" step="0.001" value="0"></div>
<div class="col-md-2 ornament-field"><div class="line-label mb-1">Other Weight (gm)</div><input type="number" name="other_weight_gm[]" class="form-control" min="0" step="0.001" value="0"></div>
<div class="col-md-3"><div class="line-label mb-1">Total Value (₹) *</div><input type="number" name="value[]" class="form-control line-value" min="0.01" step="0.01" value="0" required></div>
</div></div></template>
<script>
document.addEventListener('DOMContentLoaded',function(){const lines=document.getElementById('item-lines'),tpl=document.getElementById('line-template');function money(v){return '₹'+v.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}function total(){let taxable=0;document.querySelectorAll('.line-value').forEach(x=>taxable+=parseFloat(x.value)||0);const rate=parseFloat(document.getElementById('tax-percent').value)||0,gst=taxable*rate/100;document.getElementById('taxable-total').textContent=money(taxable);document.getElementById('gst-total').textContent=money(gst);document.getElementById('gross-total').textContent=money(taxable+gst)}function renumber(){document.querySelectorAll('.item-line').forEach((x,i)=>x.querySelector('.line-title').textContent='Item '+(i+1));document.querySelectorAll('.remove-line').forEach(x=>x.disabled=document.querySelectorAll('.item-line').length===1)}function mode(line){const type=line.querySelector('.item-type').value;line.querySelectorAll('.ornament-field').forEach(x=>x.style.display=type==='ornament'?'':'none');line.querySelectorAll('.diamond-field').forEach(x=>x.style.display=(type==='ornament'||type==='loose_diamond')?'':'none');line.querySelectorAll('.metal-field').forEach(x=>x.style.display=(type==='ornament'||type==='loose_gold')?'':'none');line.querySelector('.purity-field').style.display=type==='loose_diamond'?'none':'';line.querySelector('.net-label').textContent=type==='loose_gold'?'Gold Weight (gm) *':'Net Weight (gm) *'}function add(){const line=tpl.content.firstElementChild.cloneNode(true);lines.appendChild(line);line.querySelector('.item-type').addEventListener('change',()=>mode(line));line.querySelector('.remove-line').addEventListener('click',()=>{line.remove();renumber();total()});line.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',total));mode(line);renumber();total()}document.getElementById('add-line').addEventListener('click',add);document.getElementById('tax-percent').addEventListener('change',total);document.getElementById('dispatch-from').addEventListener('change',function(){document.getElementById('branch-address').textContent=this.selectedOptions[0]?.dataset.address||'Address not configured'});document.getElementById('customer-id').addEventListener('change',function(){const o=this.selectedOptions[0],parts=[o?.dataset.address,o?.dataset.gstin?'GSTIN: '+o.dataset.gstin:''].filter(Boolean);document.getElementById('customer-detail').textContent=parts.join(' · ')});add()});
</script>
<?= $this->endSection() ?>
